server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/sjhilmar/Bank-MS.git
          search-paths: config-data
  application:
    name: Bank-MS
